<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Follow what interests you.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Find out what people are talking about.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Join us in our chat.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form action="/autenticar" method="post">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Log in</button>
				</div>
			</div>
			<?php if($this->view->login == 'erro')  { ?>
				<div class="row">
					<div class="col">
						<!-- só será exibido somente se o parâmetro login for igual a erro -->
						<span class="text text-danger">*Invalid email and/or password</span>					
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img class="image" src="/img/Hearsay.png" />
				<h1 class="title">Stay up to date with all the important topics today</h1>

				<h2 class="mt-5 subtitle">Join us today!</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Sign up</a>
			</div>	
		</div>


    </div>

  </div>
</div>