<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Log out
	  	</a>
			<img src="/img/Hearsay.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">
					<!-- this is the place to put image profile -->
				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Hearsays</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets['total_tweet'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Following</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Cousins</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores['total_seguidores'] ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">

						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Hearsay</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?=$tweet['nome']?></strong> <small><span class="text text-muted">- <?=$tweet['data']?></span></small></p>
						<p><?=$tweet['tweet']?></p>		
						<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>
     						<form method="get" action="/apagar_tweet">
								<input type="hidden" name="tweet_content" value="<?= $tweet['tweet'] ?>">
								<input type="hidden" name="tweet_id" value="<?= $tweet['id'] ?>">

        						<div class="col d-flex justify-content-end">
            						<button type="submit" class="btn btn-danger">
                					<small>Delete</small></button>
        						</div>
    						</form>
						<?php } ?>						
					</div>
				</div>
			<?php } ?>

			<nav aria-label="...">
				<ul class="pagination justify-content-center">
					<li class="page-item">
						<a class="page-link" href="?pagina=1" tabindex="-1" aria-disabled="true">Previous</a>
					</li>

					<?php for($i = 1; $i <= $this->view->total_de_paginas; $i++) { ?>
						<li class="page-item <?= $this->view->pagina_ativa == $i ? 'active' : '' ?>">
							<a class="page-link" href="?pagina=<?= $i ?>"><?= $i ?></a>
						</li>
					<?php } ?>

					<li class="page-item">
						<a class="page-link" href="?pagina=<?= $this->view->total_de_paginas ?>">Next</a>
					</li>
				</ul>
			</nav>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Who follow?</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Look for acquaintances</a>
			</div>
		</div>

	</div>
</div>